### ISSUE TITLE
[suggestion] how about using docker for querydsl test environment?

### ISSUE THREAD

**Issue by heesuk-ahn** [querydsl/querydsl#2621]
In the current querydsl test environment, vagrant is used.

This environment is good, but it requires a number of pre-requisites. (VirtualBox, Puppet, Vagrant..)

If we provide various databases as docker compose, wouldn't it be simpler to build a test environment?

for example,

```
version: '2'
services:
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_USER: querydsl
      MYSQL_PASSWORD: querydsl
      MYSQL_DATABASE: querydsl
      MYSQL_ROOT_PASSWORD: querydsl
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
  postgre-sql:
    image: postgres:9.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: querydsl
      POSTGRES_PASSWORD: querydsl
      POSTGRES_DATABASE: querydsl
      POSTGRES_ROOT_PASSWORD: querydsl
    volumes:
      - /var/lib/postgresql/data
.
.
.
(Other necessary database environments...)
```
